name: RSpec
on: push

jobs:
  rspec:
    runs-on: ubuntu-16.04
    steps:
      - name: Set up Ruby 2.3
        run: |
          sudo add-apt-repository -y ppa:brightbox/ruby-ng
          sudo apt-get -y update
          sudo apt-get -y install ruby2.3 ruby2.3-dev ruby-switch
          sudo apt-get -y install ruby-switch
          sudo ruby-switch --list
          sudo ruby-switch --set ruby2.3
      - uses: actions/checkout@v2
      - name: Cache Gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-hbx_soa-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-hbx_soa-gems-${{ hashFiles('**/Gemfile.lock') }}
      - name: bundle install
        run: |
          sudo gem install bundler -v '1.15.3'
          bundle config path vendor/bundle
          bundle install
      - name: run tests
        run: |
          bundle exec rspec
